from __future__ import annotations

from typing import Protocol

from app.domain.models import (
    Book,
    BookSupplierLink,
    IncomingDelivery,
    Movement,
    PurchaseOrder,
    Supplier,
    SupplierStockEntry,
)


class BookRepository(Protocol):
    def list(self) -> list[Book]: ...

    def get(self, book_id: str) -> Book | None: ...

    def add(self, book: Book) -> Book: ...

    def update(self, book: Book) -> Book: ...

    def delete(self, book_id: str) -> bool: ...


class MovementRepository(Protocol):
    def list(self) -> list[Movement]: ...

    def get(self, movement_id: str) -> Movement | None: ...

    def add(self, movement: Movement) -> Movement: ...

    def update(self, movement: Movement) -> Movement: ...

    def delete(self, movement_id: str) -> bool: ...

    def next_id(self) -> str: ...


class SupplierRepository(Protocol):
    def list(self) -> list[Supplier]: ...

    def get(self, supplier_id: str) -> Supplier | None: ...

    def add(self, supplier: Supplier) -> Supplier: ...

    def next_id(self) -> str: ...


class PurchaseOrderRepository(Protocol):
    def list(self) -> list[PurchaseOrder]: ...

    def get(self, order_id: str) -> PurchaseOrder | None: ...

    def add(self, order: PurchaseOrder) -> PurchaseOrder: ...

    def update(self, order: PurchaseOrder) -> PurchaseOrder: ...

    def delete(self, order_id: str) -> bool: ...


class IncomingDeliveryRepository(Protocol):
    def list(self) -> list[IncomingDelivery]: ...

    def get(self, delivery_id: str) -> IncomingDelivery | None: ...

    def add(self, delivery: IncomingDelivery) -> IncomingDelivery: ...

    def delete(self, delivery_id: str) -> bool: ...


class BookSupplierLinkRepository(Protocol):
    def get_for(self, book_id: str, supplier_id: str) -> BookSupplierLink | None: ...

    def primary_for(self, book_id: str) -> BookSupplierLink | None: ...

    def upsert(self, link: BookSupplierLink) -> BookSupplierLink: ...

    def delete_for_book(self, book_id: str) -> int: ...

    def stock_for_supplier(self, supplier_id: str) -> list[SupplierStockEntry]: ...


class UnitOfWork(Protocol):
    books: BookRepository
    movements: MovementRepository
    suppliers: SupplierRepository
    purchase_orders: PurchaseOrderRepository
    incoming_deliveries: IncomingDeliveryRepository
    book_supplier_links: BookSupplierLinkRepository

    def commit(self) -> None: ...

    def rollback(self) -> None: ...

    def flush(self) -> None: ...
